version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
          RAILS_ENV: test
          RACK_ENV: test
          BUNDLE_PATH: vendor/bundle
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
      - image: circleci/postgres:10.3-alpine
        environment:
          POSTGRES_USER: root

    steps:
      - run:
          name: Install latest Chrome
          command: |
            curl -L -o /tmp/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt-get install libappindicator3-1
            sudo dpkg -i /tmp/google-chrome.deb

      - restore_cache:
          keys:
          - v1-source-{{ .Branch }}-{{ .Revision }}
          - v1-source-{{ .Branch }}-
          - v1-source-
      - checkout
      - save_cache:
          key: v1-source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - restore_cache:
          keys:
          - v1-bundle-{{ checksum "Gemfile.lock" }}
          - v1-bundle-
      - run:
          name: install dependencies
          command: |
            bundle check || bundle install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-bundle-{{ checksum "Gemfile.lock" }}

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m

      - run:
          command: bin/rake db:test:prepare

      - run:
          name: run tests
          command: |
            TEST_FILES=$(circleci tests glob "test/**/*_test.rb" | circleci tests split --split-by=timings)
            echo $TEST_FILES
            bin/rails test $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
